import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeContextWrapper } from "./contexts/ThemeContext";
import "./styles/globals.css";
import "./styles/mainScreen.css";
import "./styles/dashboard.css";
import "./styles/register.css";
import "./styles/scenes.css";
import { UserContextWrapper } from "./contexts/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserContextWrapper>
        <ThemeContextWrapper>
          <body className={inter.className}>{children}</body>
        </ThemeContextWrapper>
      </UserContextWrapper>
    </html>
  );
}
